<?xml version = "1.0" ?>
<robot xmlns:xacro = "http://www.ros.org/wiki/xacro">

    <xacro:property name = "camera_length" value = "0.01"/>
    <xacro:property name = "camera_width" value = "0.1"/>
    <xacro:property name = "camera_height" value = "0.05"/>
    <link name = "camera_link">
        <visual>
            <geometry>
                <box size = "${camera_length} ${camera_width} ${camera_height}"/>
            </geometry>
            <material name = "blue"/>
        </visual>
        <collision>
            <geometry>
                <box size = "${camera_length} ${camera_width} ${camera_height}"/>
            </geometry>
        </collision>
        <xacro:box_inertia m = "0.1" l = "${2 * camera_length}" w = "${2 * camera_width}" h = "${2 * camera_height}"
                           xyz = "0 0 0" rpy = "0 0 0"/> 
    </link>

    <link name = "camera_link_optical">
    </link>

    <joint name = "camera_optical_joint" type = "fixed">
        <origin xyz = "0 0 0" rpy = "${-pi / 2.0} 0 ${-pi / 2.0}"/>
        <parent link = "camera_link"/>
        <child link = "camera_link_optical"/>
    </joint>

    <joint name = "base_camera_joint" type = "fixed">
        <parent link = "base_link"/>
        <child link = "camera_link"/>
        <origin xyz = "${(base_length + camera_length) / 2.0} 0 ${base_height / 2.0}" rpy = "0 0 0"/>
    </joint>

    <gazebo reference = "camera_link">
        <material>Gazebo/Red</material>
        <sensor name = "camera_sensor" type = "camera">
            <pose>0 0 0 0 0 0</pose>
            <visualize>true</visualize>
            <update_rate>10.0</update_rate>
            <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
                <frame_name>camera_link_optical</frame_name>
            </plugin>
        </sensor>
    </gazebo>
</robot>