<?xml version = "1.0"?>
<robot xmlns:xacro = "http://www.ros.org/wiki/xacro">

    <xacro:property name = "base_length" value = "0.6"/>
    <xacro:property name = "base_width" value = "0.4"/>
    <xacro:property name = "base_height" value = "0.2"/>
    <xacro:property name = "wheel_radius" value = "0.1"/>
    <xacro:property name = "wheel_length" value = "0.05"/>

    <link name = "base_link">
        <visual>
            <geometry>
                <box size = "${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz = "0 0 ${base_height / 2.0}" rpy = "0 0 0" />
            <material name = "green"/>
        </visual>
        <collision>
            <geometry>
                <box size = "${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz = "0 0 ${base_height / 2.0}" rpy = "0 0 0" />
        </collision>
        <xacro:box_inertia m = "5.0" l = "${2 * base_length}" w = "${2 * base_width}" h = "${2 * base_height}" 
                           xyz = "0 0 ${base_height / 2.0}" rpy = "0 0 0"/> 
    </link>

    <xacro:macro name = "wheel_link" params = "prefix">
        <link name = "${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius = "${wheel_radius}" length = "${wheel_length}"/>
                </geometry>
                <origin xyz = "0 0 0" rpy = "${pi / 2.0} 0 0"/>
                <material name = "black"/>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius = "${wheel_radius}" length = "${wheel_length}"/>
                </geometry>
                <origin xyz = "0 0 0" rpy = "${pi / 2.0} 0 0"/>
                <material name = "black"/>
            </collision>
            <xacro:cylinder_inertia m = "1.0" r = "${2 * wheel_radius}" l = "${2 * wheel_length}"
                                 xyz = "0 0 0" rpy = "${pi / 2.0} 0 0"/>
        </link>
    </xacro:macro>
    
    <xacro:wheel_link prefix = "left"/>
    <xacro:wheel_link prefix = "right"/>

    <link name = "castor_wheel_link">
        <visual>
            <geometry>
                <sphere radius = "${wheel_radius/2.0}"/>
            </geometry>
            <origin xyz = "0 0 0" rpy = "0 0 0"/>
            <material name = "grey"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius = "${wheel_radius/2.0}"/>
            </geometry>
            <origin xyz = "0 0 0" rpy = "0 0 0"/>
            <material name = "grey"/>
        </collision>
        <xacro:castor_wheel_inertia m ="0.5" r = "${2 * wheel_radius/2.0}"
                                    xyz = "0 0 0" rpy = "0 0 0"/>
    </link>

    <link name = "basefoot_link"/>

    <joint name = "base_right_wheel_joint" type = "continuous">
        <parent link = "base_link"/>
        <child link = "right_wheel_link"/>
        <origin xyz = "-${base_length / 4.0} -${wheel_length/2.0 + base_width/2.0} 0" rpy = "0 0 0"/>
        <axis xyz = "0 1 0"/>
    </joint>

    <joint name = "base_left_wheel_joint" type = "continuous">
        <parent link = "base_link"/>
        <child link = "left_wheel_link"/>
        <origin xyz = "-${base_length / 4.0} ${wheel_length/2.0 + base_width/2.0} 0" rpy = "0 0 0"/>
        <axis xyz = "0 1 0"/>
    </joint>

    <joint name = "base_castor_wheel_joint" type = "fixed">
        <parent link = "base_link"/>
        <child link = "castor_wheel_link"/>
        <origin xyz = "${base_length / 3.0} 0 -${base_height / 4.0}" rpy = "0 0 0"/>
    </joint>

    <joint name = "basefoot_base_joint" type = "fixed">
        <parent link = "basefoot_link"/>
        <child link = "base_link"/>
        <origin xyz = "0 0 ${wheel_radius}" rpy = "0 0 0"/>
    </joint>
</robot>